version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: woragis
      POSTGRES_PASSWORD: woragis
    ports:
      - '5433:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U woragis -d auth']
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-auth-test-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - '6380:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5

  auth:
    image: woragis/woragis-auth-backend:latest
    build: .
    environment:
      ENV: 'development'
      PORT: '3000'
      DATABASE_URL: 'postgres://woragis:woragis@postgres:5432/auth?sslmode=disable'
      REDIS_URL: 'redis://redis:6379'
      AES_KEY: '0123456789abcdef0123456789abcdef'
      HASH_SALT: 'salty'
      JWT_SECRET: 'secret'
    ports:
      - '3001:3000'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres-auth-test-data:
